# Generated by Django 3.1.7 on 2021-11-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='test',
        ),
    ]
