# Generated by Django 3.1.7 on 2021-12-10 18:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='No title', max_length=100)),
                ('original_title', models.CharField(default='BD', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('availability', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('pages', models.IntegerField(null=True)),
                ('cover_type', models.CharField(choices=[('m', 'miękka okładka'), ('t', 'twarda okładka'), ('b', 'BD')], default='BD', max_length=20)),
                ('language', models.CharField(choices=[('pl', 'polski'), ('en', 'angielski'), ('de', 'niemiecki'), ('fr', 'francuski')], default='polski', max_length=20)),
                ('isbn', models.BigIntegerField(null=True)),
                ('publication_date', models.DateField(null=True)),
                ('cover_img', models.ImageField(default='covers/sample.jpg', upload_to='')),
                ('menu_img', models.CharField(blank=True, default='', max_length=1000)),
                ('book_page_img', models.CharField(blank=True, default='', max_length=1000)),
                ('size', models.CharField(default='30 x 213 x148', max_length=15, null=True)),
                ('promotional_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('number_of_items', models.IntegerField(default=0)),
                ('number_of_sold', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('num_of_likes', models.IntegerField(default=0)),
                ('author', models.ManyToManyField(to='pages.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyShopConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_num', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.TextField(blank=True, default='', max_length=30)),
                ('text', models.TextField(max_length=500)),
                ('likes', models.JSONField(default=list)),
                ('number', models.IntegerField(null=True)),
                ('book', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='pages.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('book', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='pages.book')),
                ('rev', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.book_review')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='pages.Categories'),
        ),
        migrations.AddField(
            model_name='book',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.product'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.publisher'),
        ),
        migrations.AddConstraint(
            model_name='book_review',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_review'),
        ),
        migrations.AddConstraint(
            model_name='book_rate',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_vote'),
        ),
    ]
