# Generated by Django 3.1.7 on 2021-12-27 21:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_myshopconf_pics_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='promotional_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, null=True),
        ),
    ]
