# Generated by Django 3.1.7 on 2022-01-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20220103_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_of_rates',
            field=models.IntegerField(default=0),
        ),
    ]
