# Generated by Django 3.1.7 on 2022-05-06 15:40

from decimal import Decimal
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
from pages.models import MyShopConf, Product

def populate_db(apps, schema_editor):
    MyShopConf.objects.create().save()
    Product.objects.create(name="books").save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='No title', max_length=100)),
                ('original_title', models.CharField(default='n/d', max_length=100)),
                ('description', models.TextField(blank=True, default='Ta książka nie ma jeszcze opisu.')),
                ('availability', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('promotional_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('pages', models.IntegerField(null=True)),
                ('cover_type', models.CharField(choices=[('m', 'miękka okładka'), ('t', 'twarda okładka'), ('b', 'BD')], default='BD', max_length=20)),
                ('language', models.CharField(choices=[('pl', 'polski'), ('en', 'angielski'), ('de', 'niemiecki'), ('fr', 'francuski')], default='polski', max_length=20)),
                ('isbn', models.BigIntegerField(default=0)),
                ('publication_date', models.DateField(null=True)),
                ('adding_to_shop_date', models.DateField(default=django.utils.timezone.now)),
                ('cover_img', models.ImageField(default='covers/sample.jpg', upload_to='')),
                ('book_page_img', models.CharField(blank=True, default='', max_length=1000)),
                ('menu_img', models.CharField(blank=True, default='', max_length=1000)),
                ('size', models.CharField(default='30 x 213 x148', max_length=15, null=True)),
                ('number_of_items', models.IntegerField(default=0)),
                ('number_of_sold', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('num_of_likes', models.IntegerField(default=0)),
                ('num_of_rates', models.IntegerField(default=0)),
                ('vector_column', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyShopConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_num', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('pics_num', models.IntegerField(default=0)),
                ('order_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.ManyToManyField(to='pages.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.TextField(blank=True, default='', max_length=30)),
                ('text', models.TextField(max_length=500)),
                ('likes', models.JSONField(default=list)),
                ('number', models.IntegerField(null=True)),
                ('book', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='pages.book')),
            ],
        ),
        migrations.RunPython(populate_db)
    ]
