# Generated by Django 3.1.7 on 2021-12-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshopconf',
            name='pics_num',
            field=models.IntegerField(default=100),
        ),
    ]
